-- AlterEnum
ALTER TABLE `EmailAutomation` MODIFY `trigger` ENUM('MANUAL', 'DAYS_BEFORE_APPOINTMENT', 'DAYS_AFTER_APPOINTMENT', 'ON_BOOKING_REQUESTED', 'ON_BOOKING_CONFIRMED', 'ON_QUOTE_REQUESTED') NOT NULL;
